---
title: "BST260 Final Project"
author: "Katherine Li"
date: "2022-12-03"
output: html_document
---
```{r}
library(tidyverse)
library(ggplot2)
library(caret)
library(dbplyr)
library(psych)
```

Read in data / data cleaning
```{r}
dat<-read.csv("stroke.csv")

# left with 3425 observations
dat<-dat|> filter(gender!="Other", bmi!="N/A", smoking_status!="Unknown")

dat<-dat|> 
  mutate(age_group=case_when(
  age<45~"<45",
  age>=45&age<=65~"45-65",
  age>65~">65"))|>
  mutate(BMI_group=case_when(
  as.numeric(bmi)<=18.5~"underweight",
  as.numeric(bmi)>=18.6&as.numeric(bmi)<=24.9~"normal",
  as.numeric(bmi)>=25&as.numeric(bmi)<=29.9~"overweight",
  as.numeric(bmi)>=30~"obesity"
  ))|>
  mutate(glucose_group=case_when(
  avg_glucose_level<140~"normal",
  avg_glucose_level>=140&avg_glucose_level<200~"prediabetes",
  avg_glucose_level>=200~"diabetes"
  ))|>
  mutate(age_cat=case_when(
  age<45~0,
  age>=45&age<=65~1,
  age>65~2))|>
  mutate(BMI_cat=case_when(
  as.numeric(bmi)<=18.5~0,
  as.numeric(bmi)>=18.6&as.numeric(bmi)<=24.9~1,
  as.numeric(bmi)>=25&as.numeric(bmi)<=29.9~2,
  as.numeric(bmi)>=30~3
  ))|>
  mutate(glucose_cat=case_when(
  avg_glucose_level<140~0,
  avg_glucose_level>=140&avg_glucose_level<200~1,
  avg_glucose_level>=200~2
  ))|>
  mutate(smoke_cat=case_when(
  smoking_status=="never smoked"~0,
  smoking_status=="formerly smoked"~1,
  smoking_status=="smokers"~2
  ))
```

Sample characteristic
```{r,warning=FALSE}
a=sum(dat$stroke==0)
b=sum(dat$stroke==1)

# Gender
gen<- dat|> 
        group_by(gender,stroke)|>
        summarise(count=n())
gen|>mutate(percentage=case_when(
  stroke==0~count/(a),
  stroke==1~count/(b)))|>
  ggplot(aes(stroke,percentage,fill=gender))+
  geom_bar(stat="identity",alpha=0.5)+
  scale_x_discrete(limits=c(0,1))+
  ggtitle("Stroke vs. Gender")

# Age
age<- dat|> 
        group_by(age_group,stroke)|>
        summarise(count=n())
age|>mutate(percentage=case_when(
  stroke==0~count/(a),
  stroke==1~count/(b)))|>
  ggplot(aes(stroke,percentage,fill=age_group))+
  geom_bar(stat="identity",alpha=0.5)+
  scale_x_discrete(limits=c(0,1))+
  ggtitle("Stroke vs. Age Group")

# Hypertension
hyper<- dat|> 
        group_by(hypertension,stroke)|>
        summarise(count=n())
hyper|>mutate(percentage=case_when(
  stroke==0~count/(a),
  stroke==1~count/(b)))|>
  ggplot(aes(stroke,percentage,fill=hypertension))+
  geom_bar(stat="identity",alpha=0.5)+
  scale_x_discrete(limits=c(0,1))+
  ggtitle("Stroke vs. Hypertension")

# Heart disease
heart <-dat|> 
        group_by(heart_disease,stroke)|>
        summarise(count=n())
heart|>mutate(percentage=case_when(
  stroke==0~count/(a),
  stroke==1~count/(b)))|>
  ggplot(aes(stroke,percentage,fill=heart_disease))+
  geom_bar(stat="identity",alpha=0.5)+
  scale_x_discrete(limits=c(0,1))+
  ggtitle("Stroke vs. Heart Disease")

# Marital
marital<-dat|> 
        group_by(ever_married,stroke)|>
        summarise(count=n())
marital|>mutate(percentage=case_when(
  stroke==0~count/(a),
  stroke==1~count/(b)))|>
  ggplot(aes(stroke,percentage,fill=ever_married))+
  geom_bar(stat="identity",alpha=0.5)+
  scale_x_discrete(limits=c(0,1))+
  ggtitle("Stroke vs. Marital")

# Work type
work<-dat|> 
        group_by(work_type,stroke)|>
        summarise(count=n())
work|>mutate(percentage=case_when(
  stroke==0~count/(a),
  stroke==1~count/(b)))|>
  ggplot(aes(stroke,percentage,fill=work_type))+
  geom_bar(stat="identity",alpha=0.5)+
  scale_x_discrete(limits=c(0,1))+
  ggtitle("Stroke vs. Work Type")

# Residence type
resi<-dat|> 
        group_by(Residence_type,stroke)|>
        summarise(count=n())
resi|>mutate(percentage=case_when(
  stroke==0~count/(a),
  stroke==1~count/(b)))|>
  ggplot(aes(stroke,percentage,fill=Residence_type))+
  geom_bar(stat="identity",alpha=0.5)+
  scale_x_discrete(limits=c(0,1))+
  ggtitle("Stroke vs. Residence Type")

# Average glucose level
glu<- dat|> 
        group_by(glucose_group,stroke)|>
        summarise(count=n())
glu|>mutate(percentage=case_when(
  stroke==0~count/(a),
  stroke==1~count/(b)))|>
  ggplot(aes(stroke,percentage,fill=glucose_group))+
  geom_bar(stat="identity",alpha=0.5)+
  scale_x_discrete(limits=c(0,1))+
  ggtitle("Stroke vs. Diabetes Group")


# BMI
BMI<- dat|> 
        group_by(BMI_group,stroke)|>
        summarise(count=n())
BMI|>mutate(percentage=case_when(
  stroke==0~count/(a),
  stroke==1~count/(b)))|>
  ggplot(aes(stroke,percentage,fill=BMI_group))+
  geom_bar(stat="identity",alpha=0.5)+
  scale_x_discrete(limits=c(0,1))+
  ggtitle("Stroke vs. Obesity Group")


# Smoking status
smok<-dat|> 
        group_by(smoking_status,stroke)|>
        summarise(count=n())
smok|>mutate(percentage=case_when(
  stroke==0~count/(a),
  stroke==1~count/(b)))|>
  ggplot(aes(stroke,percentage,fill=smoking_status))+
  geom_bar(stat="identity",alpha=0.5)+
  scale_x_discrete(limits=c(0,1))+
  ggtitle("Stroke vs. Smoking Status")
```

```{r}
# test
gen
hyper
heart
marital
work
resi
smok
mean(dat$age[dat$stroke==1])
mean(dat$age[dat$stroke==0])
mean(as.numeric(dat$bmi[dat$stroke==1]))
mean(as.numeric(dat$bmi[dat$stroke==0]))
mean(dat$avg_glucose_level[dat$stroke==1])
mean(dat$avg_glucose_level[dat$stroke==0])
```

Create training and test sets
```{r}
set.seed(1)
test_index <- createDataPartition(dat$stroke,times=1,p=0.2,list=FALSE)
test_set <- dat[test_index,]
train_set <-dat[-test_index,]
```

Attempt simple logistic regression - Predict stroke by age only
```{r}
age_plot<-dat|>
  ggplot(aes(age,stroke,group=factor(gender),col=gender))+
  geom_jitter(width=0,height=0.05)+
  scale_color_manual(values=c("lightcoral","lightsteelblue"))
age_plot

ggplot(dat,aes(age,stroke,color=gender))+
  geom_jitter(width=0,height=0.05)+
  geom_smooth(method="glm",method.args=list(family="binomial"))+
  facet_wrap(~gender)+
  scale_color_manual(values=c("lightcoral","lightsteelblue"))

logit_mod=glm(stroke~age,data=train_set,family="binomial")
summary(logit_mod)
predicted=predict(logit_mod,newdata=test_set,type="response")

age_logit_plot<-age_plot+
  geom_line(data=data.frame(age=test_set$age,stroke=predicted,gender=test_set$gender))
age_logit_plot


```

Fit Logistic regression model
```{r}
# Fit Logistic Regression
summary(glm(stroke~factor(age_cat)+factor(gender)+factor(hypertension)+factor(heart_disease)+factor(ever_married)+factor(work_type)+factor(Residence_type)+factor(glucose_cat)+factor(BMI_cat)+factor(smoke_cat),data=train_set,family="binomial"))

# Final Model
summary(glm(stroke~factor(age_cat)+factor(hypertension)+factor(heart_disease)+factor(glucose_cat),data=train_set,family="binomial"))

# Prediction
glm_fit <- train_set|>glm(stroke~factor(age_cat)+factor(hypertension)+factor(heart_disease)+factor(glucose_cat),data=_,family="binomial")
p_hat_logit<- predict(glm_fit,newdata=test_set,type="response")

probs<-seq(0.01, 1, length.out = 50)

PRC<-map_df(probs, function(p){
y_hat_logit<- ifelse(p_hat_logit>p,1,0)|>factor()
list(p=p,
     recall=confusionMatrix(y_hat_logit, factor(test_set$stroke))$byClass[["Sensitivity"]],
     precision=confusionMatrix(y_hat_logit, factor(test_set$stroke))$byClass[["Pos Pred Value"]])})

PRC

PRC|>
  ggplot(aes(recall,precision))+
  geom_point()+
  geom_line()+
  ylim(c(0,1))

# choose p=0.0504 as the cutoff point
y_hat_logit<- ifelse(p_hat_logit>0.0504,1,0)|>factor()
confusionMatrix(y_hat_logit, factor(test_set$stroke))
```







